name: Upload Artifact Demo

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create report file
        run: echo "This is my daily backup report" > report.txt

      - name: Upload report.txt
        uses: actions/upload-artifact@v3
        with:
          name: daily-report
          path: report.txt
